/** Bindings generated by `wrangler types` from wrangler.jsonc. */
export type AppEnv = Env

export interface Identity {
  email: string
  name: string
}

export interface HonoEnv {
  Bindings: AppEnv
  Variables: {
    /** Set by `withIdentity`; null when the request is anonymous. */
    identity: Identity | null
    /** Set by `withIdentity`; true when a token was presented but refused. */
    authStale: boolean
  }
}
